/**
 * The dawn shift on the golden path (GDD §17.2; the owner's note that the walk from the Porta
 * Capena was empty): the people who are already out in the street below the Palatine between the
 * fourth watch and the sixth hour, from the beggar under the arch to the augur on the slope. They
 * stand at the street stations of src/content/places.ts (STREET_SPOTS) and at the shrines on the
 * way, so that a player walking from the cart stand to the Velabrum is never more than about
 * forty metres from someone with a name, a trade, a voice and something to say. All are invented
 * [G] ordinary Romans doing ordinary things (Juvenal 3, Martial 12.57, Horace, Ovid); none holds
 * a real office. Their short dialogues are in src/dialogue/content/street.ts.
 *
 * Schedules use `sleep` for "gone home": the population module does not spawn a sleeper.
 */
import { at, shift } from '../../content/hours';
import { archetype } from '../../content/profiles';
import type { NpcDef } from '../types';

const npcs: NpcDef[] = [
  {
    id: 'npc-capito',
    name: 'Capito',
    title: 'Old soldier, begging at the Capena Gate',
    home: 'capena-intus',
    // Beggars sleep little, and nobody sleeps under the dripping arch: he is there before dawn.
    schedule: shift('capena-intus', 'sitGround', 'v4', 'v1'),
    dialogue: 'npc-capito',
    disposition: 'friendly',
    // Bald, grey stubble, a faded soldier's cloak older than the Dacian wars, studded boots worn through.
    appearance: {
      sex: 'male', age: 'old', build: 'slight', height: 1.6, skin: '#b07d58',
      hair: { style: 'bald', color: '#cfcbc4' }, beard: 'stubble',
      garments: [{ kind: 'tunica', color: '#8e8a80' }, { kind: 'sagum', color: '#7a6248' }],
      footwear: 'caligae',
    },
    barks: ['An as for a man who held the line at Tapae! Eh? You weren’t there. I was.', 'Twenty-two years in the Thirteenth and this is my pension: the best draught in Rome, dripping on my neck.', 'Mind the drip, friend. The gate cries for every soldier it ever sent out.', 'The Dacians? Good fighters. Better than the Syrians. Say what you like about the Thracians.'],
    tags: ['plebs', 'mendicus', 'veteranus', 'dignitas:civis'],
  },
  {
    id: 'npc-crescens',
    name: 'Crescens',
    title: 'Vigil of the 5th Cohort (night patrol)',
    faction: 'vigiles',
    home: 'capena-statio',
    // Night beat from sunset to dawn along the gate, the shrine, the street sweepers and the Circus shrine; asleep by day.
    schedule: [
      { from: at('h1'), at: 'capena-statio', activity: 'sleep' },
      { from: at('v1'), at: 'capena-statio', activity: 'patrol', route: ['capena-statio', 'compitum-capenae', 'via-scopator', 'via-lucernarius', 'compitum-circi', 'via-lucernarius', 'via-scopator', 'capena-statio'] },
    ],
    dialogue: 'npc-vigiles',
    disposition: 'neutral',
    combat: archetype('vigil'),
    appearance: {
      sex: 'male', age: 'adult', build: 'average', height: 1.66, skin: '#8e5e3e',
      hair: { style: 'cropped', color: '#1b1612' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#e2dac6' }, { kind: 'paenula', color: '#7a6248' }],
      footwear: 'caligae', weapon: 'fustis',
      armor: { helmet: { kind: 'vigiles-cap' } },
    },
    barks: ['Water in the flats! Lamps out! Water in the flats!', 'Quis est? Oh. A traveller. Welcome to Rome; mind the drip.', 'Fourth watch, and the bakers are starting. Nothing to report but bread.', 'If you see smoke, shout. If you see a fire, shout louder. If you see the prefect, shout something else.'],
    tags: ['law', 'vigil', 'dignitas:latinus-iunianus'],
  },
  {
    id: 'npc-miles-valens',
    name: 'Valens',
    title: 'Soldier of the Urban Cohorts (gate post)',
    faction: 'cohortes-urbanae',
    rank: 'miles',
    home: 'capena-statio',
    schedule: [
      { from: at('v4'), at: 'capena-statio', activity: 'guard' }, // opens the gate to the first carts' tail
      { from: at('h5'), at: 'capena-statio', activity: 'guard' },
      { from: at('v1'), at: 'capena-statio', activity: 'sleep' },
    ],
    dialogue: 'npc-urbaniciani',
    disposition: 'neutral',
    combat: archetype('miles-urbanus'),
    appearance: {
      sex: 'male', age: 'adult', build: 'muscular', height: 1.72, skin: '#c99a72',
      hair: { style: 'cropped', color: '#4a3424' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#e2dac6' }, { kind: 'sagum', color: '#9e3b2e' }],
      footwear: 'caligae',
      armor: { helmet: { kind: 'imperial-italic', metal: 'iron' }, body: { kind: 'lorica-hamata', metal: 'iron' } },
      weapon: 'gladius', shield: { model: 'scutum-oval', color: '#9e3b2e', emblem: 'thunderbolt' },
    },
    barks: ['Name, trade, and where you’re going. No, the real reason.', 'Carts after the tenth hour, on foot at any time, drunk never. That’s the Prefect’s rule, not mine.', 'A man was knifed here before dawn? Not on my watch. My watch starts when the gate opens.', 'Eleven years in the cohort and not once has the arch stopped dripping.'],
    tags: ['soldier', 'official', 'law', 'dignitas:civis'],
  },
  {
    id: 'npc-miles-severus',
    name: 'Severus',
    title: 'Soldier of the Urban Cohorts (day patrol)',
    faction: 'cohortes-urbanae',
    rank: 'miles',
    home: 'capena-statio',
    // The daytime patrol of GDD §13.1: the gate, the Via Appia, the Circus north street.
    schedule: [
      { from: at('h2'), at: 'capena-statio', activity: 'patrol', route: ['capena-statio', 'via-lucernarius', 'compitum-circi', 'circi-ficus', 'astrologi-circi', 'schola-viae', 'astrologi-circi', 'circi-ficus', 'compitum-circi', 'via-lucernarius', 'capena-statio'] },
      { from: at('v1'), at: 'capena-statio', activity: 'sleep' },
    ],
    dialogue: 'npc-urbaniciani',
    disposition: 'neutral',
    combat: archetype('miles-urbanus', { kit: 1 }),
    appearance: {
      sex: 'male', age: 'adult', build: 'stocky', height: 1.67, skin: '#b07d58',
      hair: { style: 'curly-short', color: '#2a1d14' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#e2dac6' }, { kind: 'sagum', color: '#9e3b2e' }],
      footwear: 'caligae',
      armor: { helmet: { kind: 'imperial-gallic', metal: 'iron' }, body: { kind: 'lorica-segmentata', metal: 'iron' } },
      weapon: 'gladius', shield: { model: 'scutum', color: '#9e3b2e', emblem: 'thunderbolt' },
    },
    barks: ['Move along. The street’s for walking, not for standing in the middle of.', 'Fans, astrologers and carters: the three plagues of the Circus road.', 'No brawling below the Palatine. The emperor can hear you from up there.', 'If you’re lost, the Forum is that way. If you’re not lost, why are you standing there?'],
    tags: ['soldier', 'official', 'law', 'dignitas:civis'],
  },
  {
    id: 'npc-gaudens',
    name: 'Gaudens',
    title: 'Street sweeper (a slave of the aediles)',
    home: 'via-scopator',
    schedule: shift('via-scopator', 'sweep', 'v4', 'h12'),
    dialogue: 'npc-gaudens',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'slight', height: 1.62, skin: '#8e5e3e',
      hair: { style: 'curly-short', color: '#1b1612' }, beard: 'none',
      garments: [{ kind: 'tunica-short', color: '#7a6248' }],
      footwear: 'barefoot',
    },
    barks: ['Sweep, sweep, sweep. They throw it down, I sweep it up. That is Rome.', 'Mind the heaps. Careful: the left one moves.', 'The Prefect of the City says the street is clean when it is clean. The street says otherwise.', 'My name means “joyful”. My master’s a humorist.'],
    tags: ['servus', 'faber', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-mancinus',
    name: 'Mancinus',
    title: 'Charcoal seller',
    home: 'via-carbonarius',
    schedule: shift('via-carbonarius', 'stand', 'v4', 'h11'),
    dialogue: 'npc-mancinus',
    disposition: 'friendly',
    // Black to the elbows: the only man in Rome whose tunica is grimier than the Cloaca’s.
    appearance: {
      sex: 'male', age: 'middle', build: 'stocky', height: 1.63, skin: '#b07d58',
      hair: { style: 'cropped', color: '#2a1d14' }, beard: 'stubble',
      garments: [{ kind: 'tunica-short', color: '#3b342f' }, { kind: 'apron', color: '#3b342f' }],
      footwear: 'barefoot',
    },
    barks: ['Charcoal! Beech charcoal for the kitchen, oak for the forge, bargains for the brave!', 'Every kitchen in Rome burns my charcoal and blames the smoke on me.', 'Cooks! Bakers! Anybody who wants a house still standing at dawn: buy a lid for your brazier.', 'The donkey’s name is Cicero. He talks a lot and carries nothing.'],
    tags: ['plebs', 'faber', 'dignitas:libertus'],
  },
  {
    id: 'npc-epagathus',
    name: 'Epagathus',
    title: 'Lamp-seller',
    home: 'via-lucernarius',
    schedule: shift('via-lucernarius', 'talk', 'v4', 'h12'),
    dialogue: 'npc-epagathus',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'middle', build: 'slight', height: 1.64, skin: '#c99a72',
      hair: { style: 'receding', color: '#4a3424' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#cc9a35' }, { kind: 'apron', color: '#e2dac6' }],
      footwear: 'soleae',
    },
    barks: ['Lamps! Clay lamps with a gladiator on the lid! Lamps with Venus on the lid, for the discreet!', 'Light is cheap. Darkness costs you teeth.', 'One as for the lamp, one for the oil, and the wick’s free, because I’m not a thief.', 'On the Lemuria nights nobody buys a lamp. They all light every lamp they own. Funny, that.'],
    tags: ['plebs', 'tabernarius', 'dignitas:libertus'],
  },
  {
    id: 'npc-cornix',
    name: 'Cornix',
    title: 'Carter with a broken wheel',
    home: 'via-plaustrum',
    // The night carts must be off the streets by sunrise; a broken wheel is how he is still here at the second hour.
    schedule: shift('via-plaustrum', 'work', 'v4', 'h4'),
    dialogue: 'npc-cornix',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'middle', build: 'muscular', height: 1.7, skin: '#b07d58',
      hair: { style: 'cropped', color: '#1b1612' }, beard: 'stubble',
      garments: [{ kind: 'tunica-short', color: '#7a6248' }, { kind: 'paenula', color: '#5a4632' }],
      footwear: 'barefoot',
    },
    barks: ['Hold the wheel, will you? No, the other wheel. No, THAT one.', 'The aedile’s men will fine me for blocking the road. I will fine the wheel.', 'Marble for the Forum of Trajan! Marble that weighs more than the emperor’s conscience.', 'Night carts, they say. Night wheels, I say; the day wheel is the one that breaks.'],
    tags: ['plebs', 'plaustrarius', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-trophimus',
    name: 'Trophimus',
    title: 'Attendant of the crossroads shrine',
    home: 'compitum-circi',
    schedule: shift('compitum-circi', 'sweep', 'v4', 'h9'),
    dialogue: 'npc-trophimus',
    disposition: 'friendly',
    // A freedman minister of the vicus; wears the little altar-boy’s white tunic of his office.
    appearance: {
      sex: 'male', age: 'adult', build: 'average', height: 1.65, skin: '#c99a72',
      hair: { style: 'curly-short', color: '#4a3424' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#efe8d8', trim: '#5b1f3b' }],
      footwear: 'soleae',
    },
    barks: ['Lares of the crossroads, keep this street and this lamp.', 'A pinch of incense costs an as. The Lares keep the receipts.', 'Yesterday’s flowers have to go. The Lares prefer fresh, and so does the vicomagister.', 'Pray, citizen. It takes a moment, and the street has been very kind to you so far.'],
    tags: ['plebs', 'pious', 'dignitas:libertus'],
  },
  {
    id: 'npc-latinus',
    name: 'Latinus',
    title: 'Mime and street entertainer',
    home: 'circi-mimus',
    schedule: shift('circi-mimus', 'wander', 'h2', 'v1'),
    dialogue: 'npc-latinus',
    disposition: 'friendly',
    // A clown’s patched tunic, a white-powdered face, one yellow sock: the mimus of the Circus gate.
    appearance: {
      sex: 'male', age: 'adult', build: 'slight', height: 1.68, skin: '#ddb48f',
      hair: { style: 'curly-short', color: '#6b3a22' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#9c4a3a' }, { kind: 'lacerna', color: '#e0a526' }],
      footwear: 'barefoot',
    },
    barks: ['Ladies and gentlemen and whatever the Greeks are, a tragedy in one act: my purse.', 'I do Jupiter and the cuckolded husband. The crowd likes the husband.', 'Throw an as and I’ll be Trajan. Throw two and I’ll be somebody you can criticise.', 'Look! The senator slips on the banana. No: on the fig. There are no bananas in this reign.'],
    tags: ['plebs', 'histrio', 'dignitas:libertus'],
  },
  {
    id: 'npc-caunea',
    name: 'Caunea',
    title: 'Fig seller',
    home: 'circi-ficus',
    schedule: shift('circi-ficus', 'stand', 'h1', 'v1'),
    dialogue: 'npc-caunea',
    disposition: 'friendly',
    // Named for her wares (Cauneae figs, the cry that Cicero turned into a pun): a freedwoman from Caunus.
    appearance: {
      sex: 'female', age: 'middle', build: 'stocky', height: 1.55, skin: '#c99a72',
      hair: { style: 'veiled', color: '#4a3424' },
      garments: [{ kind: 'tunica-long', color: '#e0a526' }, { kind: 'palla', color: '#8e8a80' }, { kind: 'apron', color: '#e2dac6' }],
      footwear: 'soleae',
    },
    barks: ['Figs! Figs from Caunus! Eat them before the races, cry after!', 'Dried figs, green figs, figs for the gods! A fig for you, citizen, and one for your mother.', 'The last Caunean who called these figs “ordinary” was fed to the lions, and rightly.', 'Greens or Blues? Both buy figs. I am for whoever pays.'],
    tags: ['plebs', 'tabernarius', 'dignitas:libertus'],
  },
  {
    id: 'npc-niger',
    name: 'Sextus Niger',
    title: 'Sausage seller (botularius)',
    home: 'circi-botularius',
    schedule: shift('circi-botularius', 'work', 'h1', 'v1'),
    dialogue: 'npc-niger',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'middle', build: 'heavy', height: 1.66, skin: '#8e5e3e',
      hair: { style: 'bald', color: '#1b1612' }, beard: 'none',
      garments: [{ kind: 'tunica-short', color: '#e2dac6' }, { kind: 'apron', color: '#9c4a3a' }],
      footwear: 'barefoot',
    },
    barks: ['Hot sausages! Lucanian, spiced, and nobody asks what’s in them!', 'A dog stole one of these yesterday. He came back for another.', 'Pork, pepper and a secret. The secret is more pork.', 'Chariots at noon, sausages at dawn. A man should be fed before he loses his money.'],
    tags: ['plebs', 'tabernarius', 'dignitas:libertus'],
  },
  {
    id: 'npc-lucrio',
    name: 'Lucrio',
    title: 'Fan of the Greens',
    home: 'circi-factiones',
    // Chalks PRASINA VINCIT on the Circus wall at first light; his rival wipes it out an hour later.
    schedule: shift('circi-factiones', 'work', 'h1', 'h8'),
    dialogue: 'npc-factio-fans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'young', build: 'slight', height: 1.67, skin: '#ddb48f',
      hair: { style: 'curly-short', color: '#b08a4a' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#3e7a44' }],
      footwear: 'soleae',
    },
    barks: ['Green wins! Green wins! Green wins, and the Blues can’t spell!', 'Hierax! Hierax! Two hundred wins and he’s still a slave. That’s how good he is.', 'Chalk’s cheaper than paint and it lasts exactly as long as the vigiles’ patience.', 'The Blues will lose tomorrow. They lost yesterday too, but it was cloudy.'],
    tags: ['plebs', 'arena-fan', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-sabellus',
    name: 'Sabellus',
    title: 'Fan of the Blues',
    home: 'circi-factiones',
    schedule: shift('circi-factiones', 'sit', 'h2', 'h9'),
    dialogue: 'npc-factio-fans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'average', height: 1.69, skin: '#c99a72',
      hair: { style: 'cropped', color: '#4a3424' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#3a5d8f' }],
      footwear: 'soleae',
    },
    barks: ['Blue wins! Blue always wins, if you wait long enough and the Greens fall off.', 'Look at that wall. A child could have chalked it better. A Green child.', 'Aquilo takes the inside line at every turn. A man who loves the post, and the post loves him back.', 'My wife says I love the Blues more than her. She’s right. The Blues have never complained about my cooking.'],
    tags: ['plebs', 'arena-fan', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-chaerea',
    name: 'Chaerea',
    title: 'Schoolmaster (litterator)',
    home: 'schola-viae',
    schedule: shift('schola-viae', 'talk', 'h1', 'h6', 0.4),
    dialogue: 'npc-chaerea',
    disposition: 'neutral',
    // A thin Greek with a cane and a wax tablet, teaching three boys in a doorway before the shops open.
    appearance: {
      sex: 'male', age: 'middle', build: 'slight', height: 1.66, skin: '#ddb48f',
      hair: { style: 'receding', color: '#8a8580' }, beard: 'short',
      garments: [{ kind: 'tunica-long', color: '#e2dac6' }, { kind: 'lacerna', color: '#a5916c' }],
      footwear: 'soleae',
    },
    barks: ['Again! “Arma virumque cano…” Louder! The coppersmiths can hear you, so can I!', 'A boy who can’t parse Virgil can’t read a contract, and a man who can’t read a contract signs it.', 'Eight asses a month per boy, and a gift at the Saturnalia. Nobody pays the gift. I have a long memory.', 'In Athens they’d have been discussing the soul by now. Here we’re still on the verb.'],
    tags: ['plebs', 'ludi-magister', 'dignitas:libertus', 'greek'],
  },
  {
    id: 'npc-sabinus',
    name: 'Sabinus',
    title: 'Water carrier (aquarius)',
    home: 'via-aquarius',
    schedule: shift('via-aquarius', 'work', 'v4', 'h12'),
    dialogue: 'npc-sabinus',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'muscular', height: 1.68, skin: '#b07d58',
      hair: { style: 'cropped', color: '#2a1d14' }, beard: 'stubble',
      garments: [{ kind: 'tunica-short', color: '#4f6e6a' }],
      footwear: 'barefoot',
    },
    barks: ['Water! Water up the stairs, an as a jar! The fifth floor gets the fresh!', 'Seven flights, ten jars, and nobody tips. That’s why I’m a philosopher.', 'The Aqua Marcia is the best water in Rome. The Aqua Marcia is also the dearest. Go figure.', 'Up the stairs they want it cold. Down the stairs they want it gone.'],
    tags: ['plebs', 'servus', 'aquarius', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-dorcas',
    name: 'Dorcas',
    title: 'Goat-milk seller',
    home: 'via-capraria',
    schedule: shift('via-capraria', 'stand', 'v4', 'h7'),
    dialogue: 'npc-dorcas',
    disposition: 'friendly',
    // Street goat-herds milking at the customer’s door are a Roman sight [P]. A herder’s long tunic and a stick.
    appearance: {
      sex: 'female', age: 'middle', build: 'stocky', height: 1.52, skin: '#c99a72',
      hair: { style: 'veiled', color: '#8a8580' },
      garments: [{ kind: 'tunica-long', color: '#7a6248' }, { kind: 'palla', color: '#8e8a80' }],
      footwear: 'barefoot',
    },
    barks: ['Milk! Milk straight from the goat, no questions, no water, no chalk!', 'Hold the cup, citizen. Don’t hold the goat. She bites.', 'Warm milk at dawn and wine at dusk. That is how my mother lived to ninety.', 'The little one is called Pontifex. He eats everything, including sacred things.'],
    tags: ['plebs', 'tabernarius', 'dignitas:libertus'],
  },
  {
    id: 'npc-postumius',
    name: 'Aulus Postumius Rufinus',
    title: 'Augur, watching the birds',
    home: 'via-augur',
    // The augurs took the auspices at dawn from the Palatine; he stands with his lituus and a very bored slave.
    schedule: shift('via-augur', 'guard', 'v4', 'h6'),
    dialogue: 'npc-postumius',
    disposition: 'neutral',
    essential: true,
    appearance: {
      sex: 'male', age: 'old', build: 'average', height: 1.7, skin: '#c99a72',
      hair: { style: 'receding', color: '#cfcbc4' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#e2dac6', clavi: 'wide', trim: '#5b1f3b' }, { kind: 'toga', color: '#efe8d8', trim: '#5b1f3b' }],
      footwear: 'calcei',
    },
    barks: ['Silence, citizens: the augur is watching the birds.', 'Three eagles on the left, one crow on the right. The gods are divided. So is the Senate.', 'I have been taking the auspices for thirty years and the birds have never once been wrong. Only the interpreters.', 'Hush. A raven. That is either excellent news or the worst news. I will tell you which in an hour.'],
    tags: ['elite', 'pious', 'augur', 'dignitas:senator'],
  },
  {
    id: 'npc-aufidia',
    name: 'Aufidia',
    title: 'Matron with a child, at the crossroads shrine',
    home: 'compitum-capenae',
    schedule: shift('compitum-capenae', 'pray', 'h1', 'h5'),
    dialogue: 'npc-aufidia',
    disposition: 'friendly',
    appearance: {
      sex: 'female', age: 'adult', build: 'average', height: 1.55, skin: '#ddb48f',
      hair: { style: 'braided-crown', color: '#4a3424' },
      garments: [{ kind: 'tunica-long', color: '#4f6e6a' }, { kind: 'stola', color: '#9c4a3a' }, { kind: 'palla', color: '#e2dac6' }],
      footwear: 'soleae',
    },
    barks: ['Lares of the crossroads, keep my husband’s feet from wine and his purse from dice.', 'A honey cake for the Lares, a smaller one for the boy, and none for my husband.', 'Come here, Gaius. Don’t touch the shrine. The god is not a toy.', 'Mercury, if you’re listening: a little less rain on the gate this year.'],
    tags: ['plebs', 'matrona', 'pious', 'dignitas:civis'],
  },
  {
    id: 'npc-hilarus',
    name: 'Hilarus',
    title: 'Lamp-tender of the Vicus Tuscus (a public slave)',
    home: 'seplasia-vici-tusci',
    // Snuffs the street lamps of the Vicus Tuscus at first light and trims them at dusk.
    schedule: [
      { from: at('v4'), at: 'seplasia-vici-tusci', activity: 'patrol', route: ['via-tusci-alta', 'seplasia-vici-tusci', 'popina-vici-tusci', 'compitum-vici-tusci', 'taberna-collapsa', 'compitum-vici-tusci', 'popina-vici-tusci', 'seplasia-vici-tusci'] },
      { from: at('h4'), at: 'seplasia-vici-tusci', activity: 'sleep' },
      { from: at('h12'), at: 'compitum-vici-tusci', activity: 'work' },
      { from: at('v2'), at: 'compitum-vici-tusci', activity: 'sleep' },
    ],
    dialogue: 'npc-hilarus',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'slight', height: 1.64, skin: '#8e5e3e',
      hair: { style: 'cropped', color: '#1b1612' }, beard: 'none',
      garments: [{ kind: 'tunica-short', color: '#7a6248' }],
      footwear: 'barefoot', weapon: 'torch',
    },
    barks: ['Lamps out! The sun’s up, and it burns for free!', 'Oil costs a quadrans a lamp. The aediles want it saved, the people want it lit. I trim.', 'Mind the ladder. The last man to stand under it asked for a hat.', 'On the ghost nights they want every lamp burning. I’ve been up since the first watch.'],
    tags: ['servus', 'publicus', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-licinia',
    name: 'Licinia',
    title: 'Garland seller at the head of the Vicus Tuscus',
    home: 'via-tusci-alta',
    schedule: shift('via-tusci-alta', 'stand', 'h1', 'v1'),
    dialogue: 'npc-licinia',
    disposition: 'friendly',
    appearance: {
      sex: 'female', age: 'adult', build: 'average', height: 1.56, skin: '#ddb48f',
      hair: { style: 'bun', color: '#6b3a22' },
      garments: [{ kind: 'tunica-long', color: '#c77b83' }, { kind: 'palla', color: '#e2dac6' }],
      footwear: 'soleae',
    },
    barks: ['Garlands! Rose and violet for the god of the street, myrtle for the lovers!', 'Vortumnus likes fruit and flowers. He also likes a girl who pays her stall-fee.', 'A garland for tomorrow? The whole Forum will be hung with them.', 'Wreaths for the dead, wreaths for the living, wreaths for the girl you shouldn’t.'],
    tags: ['plebs', 'tabernarius', 'dignitas:libertus'],
  },
];

export default npcs;
