/**
 * Colourful Romans of the v0.1 core (GDD §2.2–2.3, docs/research/society.md): the people who make
 * the streets feel like Juvenal's Rome. Juvenal is a fixed star (§2.5: essential, never killable);
 * the senator is GDD's npc-patron-vettius (a Clientela patron from v0.3, here with his clients in
 * the Forum); everyone else is fictional.
 */
import type { NpcDef } from '../types';

const npcs: NpcDef[] = [
  {
    id: 'npc-iuvenalis',
    name: 'Decimus Iunius Iuvenalis',
    title: 'Satirist',
    home: 'subura',
    schedule: [
      { from: 0, at: 'subura', activity: 'sleep' },
      // Satire 3 opens with a friend leaving Rome by the Porta Capena.
      { from: 4.5, at: 'porta-capena', activity: 'stand' },
      { from: 8, at: 'basilica-julia-steps', activity: 'sit' },
      { from: 12, at: 'popina-vicus-tuscus', activity: 'sit' },
      { from: 15, at: 'basilica-julia-steps', activity: 'talk' },
      { from: 19, at: 'subura', activity: 'sleep' },
    ],
    dialogue: 'npc-iuvenalis',
    disposition: 'neutral',
    essential: true,
    // In his fifties, a client's worn toga over a plain tunic, clean-shaven badly.
    appearance: {
      sex: 'male', age: 'middle', build: 'slight', height: 1.68, skin: '#d9ab84',
      hair: { style: 'receding', color: '#8a857d' }, beard: 'stubble',
      garments: [{ kind: 'tunica', color: '#cfc4ad' }, { kind: 'toga', color: '#d9d0bd' }],
      footwear: 'calcei',
    },
    barks: ['Fires, falling roofs, and poets reciting in August.', 'Here everything costs money.', 'Make your will before you go out to dinner.'],
    tags: ['plebs', 'dignitas:civis', 'fixed-star'],
  },
  {
    id: 'npc-vestalis-laeta',
    name: 'Iunia Laeta',
    title: 'Virgo Vestalis',
    home: 'atrium-vestae',
    schedule: [
      { from: 0, at: 'temple-vesta', activity: 'pray' },
      { from: 3, at: 'atrium-vestae', activity: 'sleep' },
      { from: 7, at: 'temple-vesta', activity: 'pray' },
      { from: 10, at: 'rostra', activity: 'travel' },
      { from: 11, at: 'atrium-vestae', activity: 'work' },
      { from: 16, at: 'temple-vesta', activity: 'pray' },
      { from: 19, at: 'atrium-vestae', activity: 'sleep' },
    ],
    dialogue: 'npc-vestalis-laeta',
    disposition: 'friendly',
    essential: true,
    appearance: {
      sex: 'female', age: 'adult', build: 'slight', height: 1.58, skin: '#dcb08c',
      hair: { style: 'vestal', color: '#3a2a1d' },
      garments: [{ kind: 'tunica-long', color: '#f2eee4' }, { kind: 'stola', color: '#ebe5d8' }, { kind: 'palla', color: '#f2eee4' }],
      footwear: 'calcei',
    },
    barks: ['Peace be on this house.', 'The fire does not go out.'],
    tags: ['elite', 'pious', 'incorruptible', 'vestal'],
  },
  {
    id: 'npc-lictor-vestae',
    name: 'Rufus',
    title: 'Lictor of the Vestals',
    home: 'atrium-vestae',
    schedule: [
      { from: 0, at: 'atrium-vestae', activity: 'sleep' },
      { from: 7, at: 'atrium-vestae', activity: 'guard' },
      { from: 10, at: 'rostra', activity: 'travel' },
      { from: 11, at: 'atrium-vestae', activity: 'guard' },
      { from: 20, at: 'atrium-vestae', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    appearance: {
      sex: 'male', age: 'adult', build: 'muscular', height: 1.74, skin: '#cf9f78',
      hair: { style: 'cropped', color: '#2a1f17' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#ebe5d6' }, { kind: 'toga', color: '#ebe5d6' }],
      footwear: 'calcei', weapon: 'fustis',
    },
    barks: ['Make way for the Virgin of Vesta!', 'Step aside.'],
    tags: ['official', 'dignitas:civis'],
  },
  {
    id: 'npc-patron-vettius',
    name: 'Sextus Vettius Crispinus',
    title: 'Senator',
    home: 'curia-julia',
    schedule: [
      { from: 0, at: 'forum-nerva', activity: 'travel' },
      { from: 8, at: 'rostra', activity: 'talk' },
      { from: 10, at: 'basilica-julia', activity: 'talk' },
      { from: 13, at: 'curia-julia', activity: 'stand' },
      { from: 15, at: 'forum-nerva', activity: 'travel' },
    ],
    dialogue: 'npc-patron-vettius',
    disposition: 'neutral',
    essential: true,
    // An old Italian senator: broad purple stripe, the toga, a face like a walnut.
    appearance: {
      sex: 'male', age: 'old', build: 'heavy', height: 1.66, skin: '#d9ab84',
      hair: { style: 'bald', color: '#cfccc5' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#f2eee4', clavi: 'wide', trim: '#4f1838' }, { kind: 'toga', color: '#f2eee4' }],
      footwear: 'calcei',
    },
    barks: ['A war in the East pays for itself, they say. They said that about Crassus.', 'Walk behind me, not beside me.'],
    tags: ['elite', 'official', 'dignitas:senator'],
  },
  {
    id: 'npc-arruns',
    name: 'Arruns',
    title: 'Haruspex by the Circus',
    home: 'circus-carceres',
    schedule: [
      { from: 0, at: 'circus-carceres', activity: 'sleep' },
      { from: 7, at: 'circus-carceres', activity: 'sit' },
      { from: 19, at: 'circus-carceres', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    services: ['vendor'],
    vendor: { stock: [{ id: 'fascinum', count: 3 }, { id: 'libum', count: 4 }], denarii: 50 },
    // An Etruscan diviner of the old school, in a pointed felt cap.
    appearance: {
      sex: 'male', age: 'old', build: 'slight', height: 1.63, skin: '#cf9f78',
      hair: { style: 'receding', color: '#a39e95' }, beard: 'short',
      garments: [{ kind: 'tunica', color: '#7d5a6a' }, { kind: 'lacerna', color: '#5b4a3a' }],
      footwear: 'soleae', armor: { helmet: { kind: 'pileus' } },
    },
    barks: ['A liver read, two denarii! The gods write on the inside.', 'Lightning on the left: good. On the right: ask me.'],
    tags: ['vendor:haruspex', 'pious', 'dignitas:civis'],
  },
  {
    id: 'npc-hippias',
    name: 'Hippias',
    title: 'Cynic philosopher',
    home: 'basilica-aemilia-tabernae',
    schedule: [
      { from: 0, at: 'basilica-aemilia-tabernae', activity: 'sleep' },
      { from: 7, at: 'rostra', activity: 'talk' },
      { from: 12, at: 'lacus-juturnae', activity: 'sitGround' },
      { from: 15, at: 'basilica-julia-steps', activity: 'talk' },
      { from: 20, at: 'basilica-aemilia-tabernae', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    // A Greek with a staff, a beard and a coarse cloak over one shoulder: the Cynic uniform.
    appearance: {
      sex: 'male', age: 'middle', build: 'slight', height: 1.7, skin: '#bd9067',
      hair: { style: 'curly-short', color: '#5c5751' }, beard: 'full',
      garments: [{ kind: 'tunica-short', color: '#8c8170' }, { kind: 'palla', color: '#6f5843' }],
      footwear: 'barefoot',
    },
    barks: ['You own nothing. Everything owns you.', 'Romans! You wash twice a day and never your souls!'],
    tags: ['plebs', 'greek', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-cerdo',
    name: 'Cerdo',
    title: 'Crier',
    home: 'rostra',
    schedule: [
      { from: 0, at: 'forum-nerva', activity: 'sleep' },
      { from: 7, at: 'rostra', activity: 'talk' },
      { from: 11, at: 'forum-trajan', activity: 'talk' },
      { from: 15, at: 'rostra', activity: 'talk' },
      { from: 19, at: 'forum-nerva', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'heavy', height: 1.69, skin: '#c6936b',
      hair: { style: 'cropped', color: '#2e2219' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#a8382a' }],
      footwear: 'soleae',
    },
    barks: ['Hear, citizens! Tomorrow at the first hour, the Column of the emperor!', 'The road to the Forum of Trajan closes at dawn! Bring no carts! Bring no dogs!'],
    tags: ['plebs', 'praeco', 'dignitas:libertus'],
  },
  {
    id: 'npc-eutyches',
    name: 'Eutyches',
    title: 'Schoolmaster',
    home: 'basilica-aemilia-tabernae',
    schedule: [
      { from: 0, at: 'forum-nerva', activity: 'sleep' },
      { from: 5.5, at: 'basilica-aemilia-tabernae', activity: 'talk' },
      { from: 12, at: 'basilica-julia-steps', activity: 'sit' },
      { from: 18, at: 'forum-nerva', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    appearance: {
      sex: 'male', age: 'old', build: 'slight', height: 1.64, skin: '#c09670',
      hair: { style: 'bald', color: '#a39e95' }, beard: 'short',
      garments: [{ kind: 'tunica', color: '#cfc4ad' }, { kind: 'palla', color: '#8a6e50' }],
      footwear: 'soleae',
    },
    barks: ['Again! Arma virumque cano…', 'Seven times eight? Seven times eight!'],
    tags: ['plebs', 'greek', 'dignitas:libertus'],
  },
  {
    id: 'npc-caecilia-paulina',
    name: 'Caecilia Paulina',
    title: 'Matron of the Velia',
    home: 'porticus-margaritaria',
    schedule: [
      { from: 0, at: 'velia-vestibule', activity: 'sleep' },
      { from: 9, at: 'porticus-margaritaria', activity: 'wander' },
      { from: 12, at: 'temple-vesta', activity: 'pray' },
      { from: 13, at: 'porticus-margaritaria', activity: 'talk' },
      { from: 17, at: 'velia-vestibule', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    appearance: {
      sex: 'female', age: 'middle', build: 'average', height: 1.57, skin: '#dcb08c',
      hair: { style: 'trajanic-tower', color: '#4a3524' },
      garments: [{ kind: 'tunica-long', color: '#e0d8c6' }, { kind: 'stola', color: '#a8382a' }, { kind: 'palla', color: '#c98b2e' }],
      footwear: 'calcei',
    },
    barks: ['Ecastor, the price of linen!', 'Walk faster, girl, and keep your eyes down.'],
    tags: ['elite', 'dignitas:eques'],
  },
  {
    id: 'npc-mamercus',
    name: 'Mamercus',
    title: 'Old soldier',
    home: 'porta-capena',
    schedule: [
      { from: 0, at: 'porta-capena', activity: 'sleep' },
      { from: 5, at: 'porta-capena', activity: 'sitGround' },
      { from: 13, at: 'circus-arcades', activity: 'sitGround' },
      { from: 18, at: 'porta-capena', activity: 'sitGround' },
      { from: 21, at: 'porta-capena', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'old', build: 'slight', height: 1.66, skin: '#bb8660',
      hair: { style: 'bald', color: '#8a857d' }, beard: 'full',
      garments: [{ kind: 'tunica', color: '#7a6a55' }, { kind: 'sagum', color: '#4e4136' }],
      footwear: 'caligae',
    },
    barks: ['An as for a man who held the line at Tapae!', 'I left a leg in Dacia. The rest of me came home.'],
    tags: ['plebs', 'soldier', 'mendicus', 'dignitas:civis'],
  },
  {
    id: 'npc-tychicus',
    name: 'Tychicus',
    title: 'Sailor of the Misenum fleet (awning crew)',
    home: 'colosseum',
    schedule: [
      { from: 0, at: 'colosseum', activity: 'sleep' },
      { from: 6, at: 'colosseum', activity: 'work' },
      { from: 12, at: 'meta-sudans-ring', activity: 'sit' },
      { from: 14, at: 'colosseum', activity: 'work' },
      { from: 19, at: 'popina-vicus-tuscus', activity: 'drunk' },
    ],
    dialogue: 'npc-romans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'young', build: 'muscular', height: 1.7, skin: '#a0744d',
      hair: { style: 'curly-short', color: '#1f1914' }, beard: 'stubble',
      garments: [{ kind: 'tunica-short', color: '#3f5f8a' }],
      footwear: 'barefoot',
    },
    barks: ['Haul! Haul! The awnings don’t raise themselves!', 'Dice? Not me. Never. Who told you?'],
    tags: ['plebs', 'soldier', 'dignitas:peregrinus'],
  },
  {
    id: 'npc-bitus',
    name: 'Bitus, son of Dida',
    title: 'Dacian captive (scaffold gang)',
    home: 'forum-trajan',
    schedule: [
      { from: 0, at: 'forum-trajan', activity: 'sleep' },
      { from: 6, at: 'column-trajan', activity: 'work' },
      { from: 12, at: 'forum-trajan', activity: 'sitGround' },
      { from: 13, at: 'column-trajan', activity: 'work' },
      { from: 19, at: 'forum-trajan', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    appearance: {
      sex: 'male', age: 'adult', build: 'muscular', height: 1.76, skin: '#dbb595',
      hair: { style: 'long-tied', color: '#5e3b22' }, beard: 'full',
      garments: [{ kind: 'tunica', color: '#8a6e50', sleeves: 'long' }, { kind: 'braccae', color: '#6f5843' }],
      footwear: 'barefoot',
    },
    barks: ['(In Dacian, under his breath.)', 'Rope. More rope.'],
    tags: ['dacian', 'servus'],
  },
  {
    id: 'npc-flavius-draco',
    name: 'Titus Flavius Draco',
    title: 'Centurion (recruiting)',
    home: 'rostra',
    schedule: [
      { from: 0, at: 'carcer-tullianum', activity: 'sleep' },
      { from: 7, at: 'rostra', activity: 'stand' },
      { from: 12, at: 'basilica-julia-steps', activity: 'talk' },
      { from: 15, at: 'circus-carceres', activity: 'stand' },
      { from: 19, at: 'carcer-tullianum', activity: 'sleep' },
    ],
    dialogue: 'npc-romans',
    disposition: 'neutral',
    appearance: {
      sex: 'male', age: 'middle', build: 'stocky', height: 1.72, skin: '#c6936b',
      hair: { style: 'cropped', color: '#5c5751' }, beard: 'none',
      garments: [{ kind: 'tunica', color: '#9b3a2a' }, { kind: 'sagum', color: '#8e3324' }, { kind: 'balteus', color: '#3b2a1c' }],
      footwear: 'caligae',
      armor: { body: { kind: 'lorica-squamata', metal: 'bronze' }, greaves: 'both' },
    },
    barks: ['Twenty years, a fair wage, land at the end. And the East is full of gold.', 'Stand up straight, lad. Can you march?'],
    tags: ['soldier', 'official', 'dignitas:civis'],
  },
  {
    id: 'npc-gnatho',
    name: 'Gnatho',
    title: 'Idler on the steps',
    home: 'basilica-julia-steps',
    schedule: [
      { from: 0, at: 'popina-vicus-tuscus', activity: 'sleep' },
      { from: 8, at: 'basilica-julia-steps', activity: 'sitGround' },
      { from: 13, at: 'popina-vicus-tuscus', activity: 'drunk' },
      { from: 15, at: 'basilica-julia-steps', activity: 'sitGround' },
      { from: 20, at: 'popina-vicus-tuscus', activity: 'drunk' },
    ],
    dialogue: 'npc-romans',
    disposition: 'friendly',
    appearance: {
      sex: 'male', age: 'adult', build: 'heavy', height: 1.65, skin: '#cf9f78',
      hair: { style: 'curly-short', color: '#4a3524' }, beard: 'stubble',
      garments: [{ kind: 'tunica', color: '#b08a4a' }],
      footwear: 'soleae',
    },
    barks: ['Six, and a dog! I win!', 'Sit, friend. Nobody in this basilica does any work.'],
    tags: ['plebs', 'dignitas:libertus'],
  },
];

export default npcs;
