/**
 * Generated by tools/music/build-samples.py from the VSCO 2 Community Edition (CC0); do not edit.
 * `midi` is the true pitch of the recording, `loop` the seamless loop region (s) of a sustained note,
 * `layer` the dynamic layer of a percussion hit (0 soft, 1 firm). Files: public/audio/music/<id>.m4a|mp3.
 */
export interface VscoSample {
  id: string;
  midi?: number;
  dur: number;
  loop?: [number, number];
  layer?: number;
}

export const VSCO: Record<string, VscoSample[]> = {
  harp: [
    {
      id: 'harp-D2',
      midi: 38,
      dur: 3.2
    },
    {
      id: 'harp-F2',
      midi: 41,
      dur: 3.2
    },
    {
      id: 'harp-A2',
      midi: 45,
      dur: 3.2
    },
    {
      id: 'harp-C3',
      midi: 48,
      dur: 3.2
    },
    {
      id: 'harp-E3',
      midi: 52,
      dur: 3.2
    },
    {
      id: 'harp-G3',
      midi: 55,
      dur: 3.2
    },
    {
      id: 'harp-B3',
      midi: 59,
      dur: 3.2
    },
    {
      id: 'harp-D4',
      midi: 62,
      dur: 3.2
    },
    {
      id: 'harp-F4',
      midi: 65,
      dur: 3.2
    },
    {
      id: 'harp-A4',
      midi: 69,
      dur: 3.2
    },
    {
      id: 'harp-C5',
      midi: 72,
      dur: 3.2
    },
    {
      id: 'harp-E5',
      midi: 76,
      dur: 3.2
    },
    {
      id: 'harp-G5',
      midi: 79,
      dur: 3.2
    }
  ],
  oboe: [
    {
      id: 'oboe-As2',
      midi: 58,
      dur: 2.551,
      loop: [
        1.1,
        2.550708
      ]
    },
    {
      id: 'oboe-D3',
      midi: 62,
      dur: 2.56,
      loop: [
        1.1,
        2.560167
      ]
    },
    {
      id: 'oboe-F3',
      midi: 65,
      dur: 2.599,
      loop: [
        1.1,
        2.599292
      ]
    },
    {
      id: 'oboe-As3',
      midi: 70,
      dur: 2.622,
      loop: [
        1.1,
        2.622125
      ]
    },
    {
      id: 'oboe-D4',
      midi: 74,
      dur: 2.57,
      loop: [
        1.1,
        2.569542
      ]
    },
    {
      id: 'oboe-F4',
      midi: 77,
      dur: 2.648,
      loop: [
        1.1,
        2.6485
      ]
    },
    {
      id: 'oboe-As4',
      midi: 82,
      dur: 2.621,
      loop: [
        1.1,
        2.62125
      ]
    },
    {
      id: 'oboe-D5',
      midi: 86,
      dur: 2.555,
      loop: [
        1.1,
        2.554833
      ]
    },
    {
      id: 'oboe-F5',
      midi: 89,
      dur: 2.654,
      loop: [
        1.1,
        2.654458
      ]
    }
  ],
  flute: [
    {
      id: 'flute-C3',
      midi: 60,
      dur: 2.352,
      loop: [
        1.0,
        2.352292
      ]
    },
    {
      id: 'flute-E3',
      midi: 64,
      dur: 2.458,
      loop: [
        1.0,
        2.457958
      ]
    },
    {
      id: 'flute-A3',
      midi: 69,
      dur: 2.375,
      loop: [
        1.0,
        2.375208
      ]
    },
    {
      id: 'flute-C4',
      midi: 72,
      dur: 2.449,
      loop: [
        1.0,
        2.448667
      ]
    },
    {
      id: 'flute-E4',
      midi: 76,
      dur: 2.403,
      loop: [
        1.0,
        2.403167
      ]
    },
    {
      id: 'flute-A4',
      midi: 81,
      dur: 2.443,
      loop: [
        1.0,
        2.443167
      ]
    },
    {
      id: 'flute-C5',
      midi: 84,
      dur: 2.454,
      loop: [
        1.0,
        2.454375
      ]
    },
    {
      id: 'flute-E5',
      midi: 88,
      dur: 2.457,
      loop: [
        1.0,
        2.456958
      ]
    }
  ],
  cello: [
    {
      id: 'cello-G1',
      midi: 43,
      dur: 4.655,
      loop: [
        1.6,
        4.655417
      ]
    },
    {
      id: 'cello-B1',
      midi: 47,
      dur: 4.58,
      loop: [
        1.6,
        4.579875
      ]
    },
    {
      id: 'cello-D2',
      midi: 50,
      dur: 4.608,
      loop: [
        1.6,
        4.607917
      ]
    },
    {
      id: 'cello-F2',
      midi: 53,
      dur: 4.598,
      loop: [
        1.6,
        4.597667
      ]
    },
    {
      id: 'cello-C3',
      midi: 60,
      dur: 4.657,
      loop: [
        1.6,
        4.657208
      ]
    }
  ],
  doum: [
    {
      id: 'doum-pp2',
      dur: 0.781,
      layer: 0
    },
    {
      id: 'doum-pp3',
      dur: 0.714,
      layer: 0
    },
    {
      id: 'doum-mp2',
      dur: 0.686,
      layer: 1
    },
    {
      id: 'doum-mp3',
      dur: 0.817,
      layer: 1
    },
    {
      id: 'doum-f4',
      dur: 0.675,
      layer: 1
    }
  ],
  tek: [
    {
      id: 'tek-h1',
      dur: 0.6,
      layer: 1
    },
    {
      id: 'tek-h2',
      dur: 0.6,
      layer: 0
    },
    {
      id: 'tek-l1',
      dur: 0.6,
      layer: 1
    }
  ],
  ka: [
    {
      id: 'ka-1',
      dur: 0.3,
      layer: 0
    },
    {
      id: 'ka-2',
      dur: 0.254,
      layer: 0
    },
    {
      id: 'ka-3',
      dur: 0.276,
      layer: 0
    }
  ],
  tambHit: [
    {
      id: 'tamb-d2',
      dur: 0.55,
      layer: 0
    },
    {
      id: 'tamb-d3',
      dur: 0.543,
      layer: 0
    },
    {
      id: 'tamb-d4',
      dur: 0.54,
      layer: 0
    }
  ],
  tambShake: [
    {
      id: 'tamb-shake',
      dur: 1.4,
      layer: 0
    },
    {
      id: 'tamb-shake2',
      dur: 1.6,
      layer: 0
    }
  ]
};
