#!/usr/bin/env python3
"""Write src/audio/music/setpieceData.ts from the two public-domain MIDI files (Wikimedia Commons).

python3 tools/music/make-setpieces.py   (needs .cache/midi/seikilos.mid and delphic.mid, see CREDITS.md)
"""
import importlib.util, json, textwrap

spec = importlib.util.spec_from_file_location('midi_dump', 'tools/music/midi-dump.py')
md = importlib.util.module_from_spec(spec)
spec.loader.exec_module(md)


def notes(path, tonic):
    d = md.parse(path)
    seen = set()
    out = []
    for t, dur, m, v, tr in d['notes']:
        k = (round(t, 3), m)
        if k in seen:  # the Delphic file doubles every note on a second channel
            continue
        seen.add(k)
        out.append([round(t, 3), round(dur, 3), m - tonic])
    return out


def ts(name, rows):
    cells = [f'[{t:g}, {d:g}, {s}]' for t, d, s in rows]
    lines = ['  ' + ', '.join(cells[i:i + 8]) + ',' for i in range(0, len(cells), 8)]
    return f'export const {name}: SetPieceNote[] = [\n' + '\n'.join(lines) + '\n];\n'


out = '''/**
 * Generated by tools/music/make-setpieces.py; do not edit.
 * Notes of two public-domain tunes taken from MIDI files on Wikimedia Commons, as
 * [start (beats), length (beats), semitones above the tonic]. See public/audio/music/CREDITS.md.
 */
export type SetPieceNote = [start: number, length: number, semitones: number];

'''
out += '/** The Epitaph of Seikilos (1st century AD), tonic A in the source; 6/8 at 60 beats per minute. */\n'
out += ts('SEIKILOS_NOTES', notes('.cache/midi/seikilos.mid', 69))
out += '\n/** The First Delphic Hymn to Apollo (c. 128 BC), reference tone B in the source file. */\n'
out += ts('DELPHIC_NOTES', notes('.cache/midi/delphic.mid', 71))
open('src/audio/music/setpieceData.ts', 'w').write(out)
print('ok')
