/**
 * "Every tier-1 landmark has a thing" (GDD §12.3, AC-23): a note or inscription to read, or a vista
 * to look at, so that seeing a place and walking to it always pays off. One entry per landmark of the
 * nine v0.1 districts (src/content/barks.ts DISTRICTS). The installer puts a "Read" or "Look" point
 * in front of each landmark's façade.
 *
 * The facts are the ones a Roman of AD 113 could know and the research docs attest (Pliny, Suetonius,
 * Livy, Josephus, Frontinus); the inscriptions are original or paraphrased, never copied, and nothing
 * is later than 113 (no Hadrianic Pantheon, no Temple of Venus and Roma, no Arch of Septimius). Texts
 * that put words on a wall are labelled invented [G] in the Lexicon.
 */
export type ThingKind = 'inscription' | 'vista' | 'note';

export interface Thing {
  /** Atlas landmark id. */
  at: string;
  kind: ThingKind;
  title: string;
  latin?: string;
  text: string;
  /** Source and confidence. */
  source: string;
}

const t = (at: string, kind: ThingKind, title: string, text: string, source: string, latin?: string): Thing => ({ at, kind, title, text, source, latin });

export const THINGS: Thing[] = [
  // ---- dist-forum-romanum
  t('miliarium-aureum', 'note', 'The Golden Milestone', 'A gilded bronze pillar, taller than a man, set up by Augustus beside the Rostra. The distances of all the roads of Italy are counted from here, it is said. What it carried is not written on it that anyone can read: only gilding, and the dirt of two generations of hands.', 'Plutarch Galba 24, Dio 54.8 [A]; the letters unknown [U]'),
  t('rostra', 'note', 'The beaks of Antium', 'Bronze ship-prows from the fleet of Antium, taken in the year 338 before the city’s second founding, still bristle from the speakers’ platform. An orator who speaks here speaks over the rams of a defeated navy. Most of them are green now.', 'Livy 8.14 [A]'),
  t('basilica-julia', 'vista', 'The courts of the Hundred', 'From the steps you can hear four courts sitting at once, each with its own advocate, each shouting at its own bench. The Hundred Judges (the centumviri) hear the great inheritance cases here. Behind the columns the water-clocks drip; an advocate who talks past his water is cut off by the bailiff.', 'Pliny Epist. 6.33, Quintilian 12.5 [A]'),
  t('basilica-aemilia', 'note', 'Phrygian marble', 'The columns of the Basilica Paulli are of coloured Phrygian marble, violet-veined, and the whole hall is said to be among the finest things in Rome. The bankers’ tables and the barber’s and the physician’s run along its front. A tablet on the nearest pier is thick with scrawled bills for lost dogs.', 'Pliny NH 36.102 [A]; the shops [P]'),
  t('temple-castor-pollux', 'inscription', 'The Twins’ rebuilt house', 'Tiberius, as a young man, rebuilt the temple in his own name and in his brother Drusus’. The podium is tall enough that the bankers keep their strongrooms in it, and tall enough for a magistrate to speak from. The doors are shut today, because it is the Lemuria.', 'Suetonius Tib. 20 [A]; the strongrooms [P]', 'TI · CAESAR · AVGVSTI · F · ET · DRVSVS · CAESAR · FRATER · DE · MANVBIIS · AEDEM · CASTORIS · ET · POLLVCIS'),
  t('temple-vesta', 'note', 'The fire that does not go out', 'A round house of marble and bronze where the Vestals keep Rome’s hearth burning. Men do not enter. If the fire goes out, Rome is said to be in danger, and the Vestal who let it die is beaten by the Pontifex in the dark. Her sisters tend it in shifts through the night.', 'Dionysius 2.67, Plutarch Numa 9 [A]'),
  t('curia-julia', 'vista', 'The Senate’s door', 'Domitian restored the Curia after the fire, and the senators still go in through the great bronze doors on the days of the Kalends and the Ides. Outside the doors stand the lictors of whoever is presiding and the clients of whoever is arriving; the quarrelling begins in the portico.', 'Chronographer of 354, Domitian’s restoration [P]'),
  t('temple-saturn', 'note', 'The treasury', 'The state’s treasury is in the podium of Saturn’s temple: the aerarium, where the quaestors keep the accounts and the army’s pay is counted out. The doors stand open on working days. The god’s feet, they say, are bound in wool all year and unbound on the Saturnalia.', 'Livy 2.21, Macrobius Sat. 1.8 [A]'),
  t('carcer-tullianum', 'note', 'The prison under the hill', 'The Tullianum is a round cell sunk in the rock, down a stair, where Rome strangled the kings she took: Jugurtha was starved here, they say, and Vercingetorix was strangled after Caesar’s triumph. The guards at the door are Urban Cohort men. Neither of them wants to talk about it.', 'Sallust Jug. 55, Plutarch Marius 12, Dio 40.41 [A]'),

  // ---- dist-capitolium
  t('temple-jupiter-capitolinus', 'vista', 'The gilded roof', 'Domitian rebuilt it for the third time, and the roof tiles are gilded: Plutarch says the gilding alone cost twelve thousand talents. From the Capitoline you can see the whole city turn pink in the morning, the Forum underneath you like a pavement of small coloured toys.', 'Plutarch Publicola 15 [A]; Suetonius Dom. 5 [A]'),
  t('asylum', 'note', 'Romulus’ refuge', 'Between the two summits of the Capitoline lies the grove where Romulus is said to have opened an asylum for runaways and outlaws, to fill his new city with men. It is still called the Asylum, and still full of those who have something to run from.', 'Livy 1.8 [A]'),
  t('temple-juno-moneta', 'note', 'The warning of the geese', 'Juno Moneta (“the Warner”) is named, they say, for the sacred geese whose cackling woke the sleeping sentries when the Gauls came up the cliff. The geese are still kept in the precinct and are still fed first, before the soldiers.', 'Livy 5.47; Cicero Div. 1.101 [A]'),
  t('tarpeian-rock', 'note', 'The cliff for traitors', 'The Tarpeian Rock is a cliff over the Forum from which traitors were thrown down. In Trajan’s reign it is mostly a place for the curious to point at. Nobody has been pushed off for years, which is thought by some to be a pity.', 'Livy 6.20, Dionysius 7.35 [A]'),

  // ---- dist-palatium
  t('domus-flavia', 'vista', 'The emperor’s dining room', 'Domitian’s great hall, the Aula Regia, is where Caesar receives. The cenatio looks over a court with a fountain shaped like a maze, and the guards at the door wear togas over their swords. Everything in the palace, they say, is polished so well that a man can see the back of his own head.', 'Suetonius Dom. 14; Martial 8.36 [A]'),
  t('domus-augustana', 'note', 'Where Caesar lives', 'Trajan lives on the hill but not in luxury: he is said to eat plain meals, walk to his own forum on foot and treat senators as friends. The doors of the Augustana look onto the Circus; on days of the games a passage of its own leads from the house to the emperor’s box.', 'Pliny Panegyricus 24, 49 [A]; the box passage [P]'),
  t('domus-tiberiana', 'note', 'The old palace', 'The oldest house of the Caesars, built over the northern edge of the hill. The imperial libraries are here. It has been Tiberius’, Caligula’s, Nero’s and Vespasian’s, and nobody who has lived in it has quite had a pleasant death.', 'Tacitus Hist. 1.27 [A]'),
  t('casa-romuli', 'note', 'The hut of Romulus', 'A hut of thatch and wattle is kept in repair on the hill’s edge, said to be Romulus’ own. Every time lightning burns it, the Pontifices rebuild it the same. It is the most expensive piece of straw in Rome.', 'Dionysius 1.79, Vitruvius 2.1.5 [A]'),
  t('temple-apollo-palatinus', 'note', 'Augustus’ Apollo', 'Augustus built it in thanks for Actium and set the Sibylline Books in the base of the god’s statue. The portico had fifty marble Danaids in front of their father and a library of Greek and Latin books on either side. A great many of the Danaids are missing a hand.', 'Suetonius Aug. 29, Propertius 2.31 [A]'),
  t('temple-magna-mater', 'note', 'The black stone', 'The Great Mother came to Rome in the form of a black stone, carried from Pessinus in the dark days of the Hannibalic War. Her priests are foreign eunuchs in saffron who may not be Roman citizens. On the Megalesia they walk through the streets with the goddess, and no Roman may follow.', 'Livy 29.10, 29.14; Dionysius 2.19 [A]'),

  // ---- dist-fora-imperialia
  t('forum-trajan', 'vista', 'The finest forum in the world', 'Apollodorus cut half a hill away to make this ground. Along the colonnades there are statues of generals in bronze, and in the centre an equestrian Trajan; behind the Basilica Ulpia the two libraries face each other across the Column’s court. Everything is new, and smells of marble dust.', 'Dio 68.16; Pliny Panegyricus 51 [A]'),
  t('basilica-ulpia', 'vista', 'The hall with the apse', 'Nearly two hundred metres of basilica, five aisles, an apse at either end, and a roof of bronze tiles. A good number of Rome’s lawyers have already moved their courts in from the old Forum, and the older ones are complaining about the walk.', 'Pausanias 5.12; Dio 68.16 [A]'),
  t('column-trajan', 'inscription', 'The dedicatory inscription', 'The Senate and People of Rome dedicate the Column to the Emperor Caesar Nerva Trajan Augustus, conqueror of the Germans and the Dacians, to show how high the hill was that was cut away for these works. A hundred feet of marble, with the war carved round it in a ribbon.', 'CIL VI 960 [A]; the Latin summarised, not quoted', 'SENATVS · POPVLVSQVE · ROMANVS · IMP · CAESARI · DIVI · NERVAE · F · NERVAE · TRAIANO · AVG · GERM · DACICO · PONTIF · MAXIMO · … · AD · DECLARANDVM · QVANTAE · ALTITVDINIS · MONS · ET · LOCVS · TANTIS · OPERIBVS · SIT · EGESTVS'),
  t('markets-trajan', 'vista', 'The market on the hill', 'The shops of the Market climb the cut hillside in six storeys of brick and travertine; the lowest give on to the street. A man can buy pepper, oil, fish, fruit, flowers and a cloak without leaving the building. The noise comes up the stairwells like heat.', 'Markets of Trajan, archaeology [A]; the trades [P]'),
  t('forum-augustus', 'note', 'The greats in the colonnades', 'Augustus filled the colonnades with statues of the heroes of Rome, from Aeneas to the generals of the Republic, each with a tablet of his deeds, so that his own should be judged by them. The Temple of Mars Ultor stands at the end, for revenge on Caesar’s murderers; the Senate debates wars and triumphs in its shadow.', 'Suetonius Aug. 31, Ovid Fasti 5.545 [A]'),
  t('forum-caesar', 'note', 'Caesar’s horse', 'In front of the Temple of Venus Genetrix, Caesar’s own horse stands in bronze, with the almost human toes on its forefeet that the old story gave it. The temple is festooned for tomorrow: the emperor is to rededicate it with his Column.', 'Suetonius Caes. 61, Pliny NH 8.155 [A]; the rededication on 12 May [P/U]'),
  t('forum-nerva', 'note', 'The Forum of Minerva', 'The Forum that is mostly a street, between the Forum of Peace and Augustus’ Forum. It was built by Domitian and finished by Nerva, and carries a frieze of working women under the eye of Minerva, goddess of weavers. Pickpockets treat the narrow bit as theirs.', 'Suetonius Dom. 5; Martial 1.2 [A]'),
  t('templum-pacis', 'vista', 'The spoils of Jerusalem', 'Vespasian’s Temple of Peace is a garden and museum in one: Greek paintings and bronzes, and the vessels of the Jewish temple carried here in Titus’ triumph, the seven-branched lamp among them. The Library of the Peace is attached. A guard walks you past the menorah and does not let you linger.', 'Josephus BJ 7.158–162; Pliny NH 34.84 [A]'),

  // ---- dist-velia
  t('arch-titus', 'note', 'The triumph in stone', 'The reliefs under the arch show the triumph of Vespasian and Titus: soldiers carrying the lamp and the silver trumpets of Jerusalem, and the emperor in his four-horse chariot with Victory behind him. The arch was finished after Titus’ death by his brother Domitian. Boys still scratch their names on the pier.', 'CIL VI 945 (the dedication) [A]'),
  t('colossus-sol', 'vista', 'The Sun’s face', 'The Colossus of Nero is a bronze giant a hundred and twenty feet tall, now with the rays of the Sun round its head and the face remade. Vespasian dedicated it to the god. Beneath it stands a scaffold: the festival of the Column is to have it regilded.', 'Suetonius Nero 31, Vesp. 18; Pliny NH 34.45 [A]; the scaffold [G]'),
  t('velia-vestibule', 'note', 'The golden house’s doorstep', 'The vestibule of Nero’s Golden House once stood here: a hall so big that it held a hundred-and-twenty-foot statue of the emperor. Vespasian gave the land back to the Romans and put the Amphitheatre where the lake had been. People still say “the house” when they point to the hill.', 'Suetonius Nero 31, Martial Spect. 2 [A]'),
  t('horrea-piperataria', 'note', 'The Pepper Warehouses', 'Domitian built the great warehouses for pepper and the other drugs of the East, and the merchants who sold them were the richest on the Sacra Via. The smell reaches the Forum on a warm morning. A customs officer sits at the gate with a pair of scales and a long list of gentlemen who are not to be upset.', 'Galen On Antidotes 1.5; Gellius 11.17 [A]'),
  t('porticus-margaritaria', 'note', 'The pearl-sellers’ arcade', 'Pearls from the Red Sea, set on black cloth in little trays at the Pearl-Sellers’ Arcade, are priced in sums that would buy a farm. The pearl-sellers’ guild is the oldest on the street: an inscription on the base of a column records their gift to the god.', 'CIL VI 9546–7: margaritarii de Sacra Via [A]'),

  // ---- dist-vallis-colossei
  t('colosseum', 'vista', 'A hundred days of games', 'Titus dedicated it in the year 80 with a hundred days of games, and wild beasts, and a naval battle in the flooded arena. Now it seats fifty thousand. The sailors of the fleet at Misenum, camped on the Caelian, work the awning: they climb the rigging like cats.', 'Suetonius Titus 7; Dio 66.25; Martial Spect. [A]'),
  t('meta-sudans', 'note', 'The Sweating Post', 'The Meta Sudans is a cone-shaped fountain of brick, rebuilt by Domitian, where the water oozes down the sides as if sweating. Gladiators wash at the basin after their training and fans argue around it on days of games. It is said to be older than the Flavian Amphitheatre, and drier.', 'the Meta Sudans, archaeology [A]; the gladiators and the fans [G]'),
  t('ludus-magnus', 'inscription', 'The Great School', 'The imperial gladiator school, built by Domitian beside the amphitheatre with a tunnel under the street to the arena itself. Above the gate: the school’s name. Under it, on the wall, in the hand of some bored tiro: “I would rather be a baker.”', 'Domitian’s Ludus Magnus, archaeology [A]; the graffito [G]', 'LVDVS · MAGNVS'),
  t('baths-titus', 'note', 'Titus’ little baths', 'The Baths of Titus are small, built in a hurry to be ready for the games, beside the amphitheatre. They have a fine marble hall and a very bad reputation for the changing room; people say the slaves who guard the clothes do so on commission.', 'Suetonius Titus 7; Martial Spect. 2.7 [A]; the reputation [G]'),
  t('curiae-veteres', 'note', 'The old assembly halls', 'The Curiae Veteres are the thirty ancient meeting-houses of the Roman tribes, where the old cult of the Curiae met. Few can say which hall belongs to which tribe now. A priest sweeps the steps for the smaller number of citizens who still come.', 'Varro LL 5.155 [A]'),

  // ---- dist-circus-maximus
  t('circus-maximus', 'vista', 'Two hundred and fifty thousand seats', 'Pliny says the Circus holds two hundred and fifty thousand; Trajan has just rebuilt it and added a new tier of seats. Twelve chariots can start in a line. The Greens, the Blues, the Reds and the Whites have their stables near the Campus: the arguments begin the night before the games.', 'Pliny NH 36.102; Pliny Panegyricus 51 [A]; Dio 68.7 [A]'),
  t('porta-capena', 'note', 'The dripping gate', 'The aqueducts of the Marcia, the Tepula and the Julia cross the old Servian gate on their arches, and the water seeps through to fall on whoever walks under. The poets call it the dripping Capena. The beggars say it is the cheapest bath in Rome, and the Appian Way, the queen of roads, starts at its foot.', 'Juvenal 3.11 (madidam Capenam); Frontinus Aq. 19 [A]'),
  t('obelisk-circus-maximus', 'inscription', 'The obelisk from the Sun’s city', 'Augustus brought this obelisk from Heliopolis in Egypt and set it on the spine of the Circus. On the sides, the old Egyptian signs tell of a king who ruled before Rome was a village. Carters point at it when they give directions to the Circus’s far end.', 'Pliny NH 36.71; the dedication to the Sun [A]', 'IMP · CAESAR · DIVI · F · AVGVSTVS · … · SOLI · DONVM · DEDIT'),
  t('pulvinar', 'note', 'The emperor’s box', 'On the Palatine side of the Circus, the pulvinar, the shrine-box where the gods’ images are set to watch the games and where the emperor sits with his family. When Trajan comes, he comes like any citizen, and people shout their petitions up to him.', 'Suetonius Aug. 45; Pliny Panegyricus 51 [A]'),
  t('arch-titus-circus', 'inscription', 'The Senate’s arch to Titus', 'An arch at the end of the Circus, set up by the Senate and People to Titus for having subdued the Jewish nation and destroyed the city of Jerusalem, which no commander before him had succeeded in taking. The statues on top are of the emperor in a four-horse chariot.', 'CIL VI 944, paraphrased [A]', 'SENATVS · POPVLVSQVE · ROMANVS · IMP · TITO · CAESARI · DIVI · VESPASIANI · F · … · GENTEM · IVDAEORVM · DOMVIT'),

  // ---- dist-velabrum-boarium
  t('forum-boarium', 'note', 'The bronze bull', 'The cattle market takes its name from the bronze bull that stands in its midst, brought from Aegina, and from the cattle sold in the shadow of Hercules’ altar. The bull is polished by the hands of everyone who wants luck in a deal. Drovers say it moos at night when a good price is coming.', 'Pliny NH 34.10; Tacitus Ann. 12.24 [A]'),
  t('temple-portunus', 'note', 'The harbour god’s house', 'A small rectangular temple of Portunus, god of harbours and of keys, beside the river on the edge of the market. The sailors who unload at the port make a vow here before every voyage; the keys of the warehouses nearby are said to be blessed on the festival of the god.', 'Varro LL 6.19; Festus [A]'),
  t('temple-hercules-victor', 'vista', 'The round temple by the river', 'The round temple of Hercules Victor, the oldest marble temple in Rome, is a ring of white columns by the cattle market. It was built by a merchant who had prospered in the oil trade and paid his vow in stone. It looks as if it were sitting on the Tiber’s edge on purpose.', 'Vitruvius 3.3.5; Servius on Aeneid 8.363 [A]'),
  t('ara-maxima', 'note', 'The Great Altar', 'Here Hercules is said to have killed Cacus and offered his cattle to the gods, and the Greatest Altar was founded. Women may not eat of the sacrifices or enter. Generals pay a tenth of their spoils at this altar and a tenth of their profits go to the god; the tithe has been paid unbroken since Hercules.', 'Livy 1.7; Macrobius Sat. 3.6 [A]'),
  t('horrea-agrippiana', 'note', 'Agrippa’s warehouses', 'The Horrea Agrippiana were built for the goods that come up the Tiber, on the Vicus Tuscus: oil, wine, grain, cloth. Agents of the great houses keep offices in the alcoves, and the clothiers’ shops and a perfumer are under the arcade. The smell of the pepper warehouses carries across the road.', 'CIL VI 9471 [A]'),
  t('portus-tiberinus', 'note', 'The river port', 'Barges and lighters unload here from Ostia and the upstream towns: oil from Baetica in round amphorae, wine from Campania, marble from Luna, and the grain for the people. The divers of the river guild are paid to find what falls overboard. They find rather more than that.', 'Strabo 5.3.7; the divers (urinatores) [A]'),
  t('sant-omobono-temples', 'note', 'The temples of Fortuna', 'The twin temples of Fortuna and Mater Matuta, founded by King Servius Tullius, were burned and rebuilt twice. A statue there is draped in a toga, they say the king’s own. Gamblers here make their vows before they go to the Circus.', 'Livy 24.47, Dionysius 4.40, Ovid Fasti 6.569 [A]'),

  // ---- dist-forum-holitorium
  t('forum-holitorium', 'note', 'The vegetable market', 'The vegetable market is older than the Republic. Its three little temples (Janus, Juno Sospita, Spes) are crowded between the stalls, and the women who sell leeks and cabbages do so under the very eaves of the gods. The oldest of them says she was born in the Forum Holitorium and has no intention of dying outside it.', 'Livy 21.62, 40.34 [A]'),
  t('theatre-marcellus', 'vista', 'Augustus’ theatre', 'Augustus dedicated the theatre to the memory of his nephew Marcellus, who died young. It seats about fifteen thousand and its outer arches are filled with shops and workshops. On the days of the Ludi Romani the whole street smells of crushed saffron.', 'Suetonius Aug. 29; Dio 43.49 [A]'),
  t('temple-aesculapius', 'note', 'The island shaped like a ship', 'Rome called Aesculapius from Epidauros in a time of plague, and the snake that came with the embassy swam ashore on this island, which the Romans carved into the shape of a ship, with the god’s snake on the prow. The sick sleep in the portico and the god heals them. Slaves abandoned here when ill are free if they live.', 'Livy 10.47, Suetonius Claud. 25 [A]'),
  t('temple-janus-holitorium', 'note', 'Janus in the market', 'Janus of the Vegetable Market, with two faces and a door: one to the war, one to the peace. The doors of his shrine in the Forum stand open for Parthia. A stallholder tells you the god’s second face gets all the cabbages.', 'Livy 40.34; Pliny NH 7.213 [A]; the stallholder [G]'),
  t('temple-spes', 'note', 'The temple of Hope', 'The little temple of Hope, the last of the three at the vegetable market. It has burned twice and been rebuilt by every generation of the people. A garland of flowers hangs from the door at the festival; the old ones say this is the only temple in Rome that is never empty.', 'Livy 21.62; Tacitus Ann. 2.49 [A]'),
];
